service: file-handler-python
frameworkVersion: '2 || 3'
variablesResolutionMode: '20210326'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: 'dev'
  region: 'eu-west-1'
  lambdaHashingVersion: '20201221'
  environment:
    SOURCE_BUCKET: '${env:SOURCE_BUCKET}'
    SOURCE_INPUT_FOLDER: '${env:SOURCE_INPUT_FOLDER}'
    SQS_FILE_INFO: '${env:SQS_FILE_INFO}'
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::${env:SOURCE_BUCKET}'
    - Effect: 'Allow'
      Action: 's3:GetObject'
      Resource: 'arn:aws:s3:::${env:SOURCE_BUCKET}/*'
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        Fn::GetAtt:
          - filesInfoQueue
          - Arn

resources:
  Resources:
    sourceBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
         BucketName: '${env:SOURCE_BUCKET}'
    logBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
         BucketName: '${env:LOG_BUCKET}'
    filesInfoQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        DelaySeconds: 0
        MaximumMessageSize: 1024
        MessageRetentionPeriod: 360
        QueueName: '${env:SQS_FILE_INFO}'
        ReceiveMessageWaitTimeSeconds: 20
        RedriveAllowPolicy:
          redrivePermission: 'denyAll'
        VisibilityTimeout: 360
  Outputs:
      filesInfoSQS:
        Description: 'The ARN for the files info SQS'
        Value:
          Fn::GetAtt:
            - filesInfoQueue
            - Arn
        Export:
          Name: '${self:service}:filesInfoSQS'


functions:
  fileHandler:
    handler: handler.process
    events:
      - s3:
          bucket:
            Ref: sourceBucket
          event: 's3:ObjectCreated:*'
          rules:
            - prefix: '${env:SOURCE_INPUT_FOLDER}/'
            - suffix: '.csv'
          existing: true
      - s3:
          bucket:
            Ref: sourceBucket
          event: 's3:ObjectCreated:*'
          rules:
            - prefix: '${env:SOURCE_INPUT_FOLDER}/'
            - suffix: '.txt'
          existing: true



package:
  patterns:
    - '!node_modules/**'
